### PR TITLE
Feature/use fetch contents

### PR DESCRIPTION
**Pull request by ClausKlein**
For Christmas I want to be a little constructive:

With modern cmake, It is possible to use `pegtl` as external header only lib

### CODE REVIEW

**Comment by d-frey** [comment]
We wanted to remove the copy of the PEGTL for a long time and replace it by a dependency, so this is certainly something that would be appreciated. We also recently looked into this topic and I'm working on it already, mostly based on a git submodule. I am following @wravery's example here, as he already shows how to do it in his repo: https://github.com/wravery/cppgraphqlgen/blob/master/CMakeLists.txt

Your PR would create a couple of issues, like breaking the Android build (which only supports CMake 3.10) and I think a submodule + add_subdirectory() would be more in line with the usual approach during development (non-developers will usually install the dependency via a package which is then found by find_package()). While I appreciate your efforts, I wonder if we could align this. Would FetchContent provide any significant benefit over my approach? (FetchContent is also not available on CMake 3.10, right?) Or do you see a problem with git submodule that I'm not aware of?

I've also committed some stylistic changes (align with other taocpp projects) to the CMakeLists.txt files. Your PR should not include those, as it should not include any clang-tidy fixes. Each PR should focus on only one thing.

**Comment by d-frey** [comment]
FYI I added / pushed the branch, it currently fails on some images due to a too old version of git. I contacted @uilianries about those images, so let's see if this can be fixed at the root or if we need to find a work-around.

**Comment by d-frey** [comment]
I hope you agree that a git submodule is the more canonical way of adding the PEGTL into taoJSON. I sorted out the issues with the new CI and merged the branch into master. I'll close this PR, but thank you for pushing the issue and if you want to add anything, could you please add it on top of the current master in a new PR? Thanks again, removing the embedded PEGTL was long overdue :)

**Comment by ClausKlein** [comment]
> I hope you agree that a git submodule is the more canonical way of adding the PEGTL into taoJSON. 

NO, with git submodule, you still have the problem, that clang-tidy with different rule set can't be handled.

A git submodule is not solving the problem that PEGTL lib may be already installed on build environment in the right version.

cmake fetch contents it the modern way to prevent this!

**Comment by d-frey** [comment]
Using all-caps words, exclamation marks and calling things "stupid" doesn't help. Also, it is not the type of discussion style I like to see in our project. Please refrain from such behavior in the future.

We also made it very clear that we don't think that there is a problem with clang-tidy. We asked you to provide actual evidence/arguments against it, which you didn't. So, please stop trying to fix it.

Even if there were a problem with clang-tidy, that has nothing to do with whether we use a git submodule or not.

Also, agagin, do not mix multiple things into a single PR. Trying to sneak in clang-tidy "fixes" with FetchContent will not happen.

Finally, FetchContent is not supported on older versions of CMake which are still needed because we have environments which we can not simply upgrade. git submodules work and there are probably other ways to automate how much it affects users. I remember seeing some of these and I will try and improve the situation as time permits.

**Pull request closed without merging**
