### PR TITLE
Fix bug in array_traits::to

### PR DESCRIPTION
**Pull request by revtronix**
array_traits::to causes std::logic_error exception to be thrown when converting array elements. I have added a test which triggers the bug and also the fix.

### CODE REVIEW

**Comment by ColinH** [comment]
> `/Users/runner/work/json/json/include/tao/json/span.hpp:484:21: error: out-of-line definition of 'get' does not match any declaration in namespace 'std'`
> `constexpr auto std::get( tao::span< ElementType, Extent > s ) noexcept -> ElementType&  // NOLINT(modernize-use-nodiscard)`

@d-frey Missing include?

**Comment by ColinH** [comment]
@revtronix Thanks for the fix, if you could just add a couple of spaces where necessary to adhere to our code formatting...

**Comment by d-frey** [comment]
> > `/Users/runner/work/json/json/include/tao/json/span.hpp:484:21: error: out-of-line definition of 'get' does not match any declaration in namespace 'std'`
> > `constexpr auto std::get( tao::span< ElementType, Extent > s ) noexcept -> ElementType&  // NOLINT(modernize-use-nodiscard)`
> 
> @d-frey Missing include?

Nope, the include is there. It's a problem with the namespace, I fixed it. But the overload is not actually legal anyways, long term we should think about what to do with `tao::span`. It would probably be best to remove it. Anyways, it should be fixed for now.

**Comment by ColinH** [comment]
Ok, merged this PR, thanks again, will fix formatting.

**Pull request merged**
