### PR TITLE
Fix windows (cl.exe) build

### PR DESCRIPTION
**Pull request by mallexxx**
tao::json::binding::member_kind::OPTIONAL is conflicting with Windows define OPTIONAL, defined in minwindef.h which is imported automatically when importing iostream, causing build errors.

1st suggested commit does #undef OPTIONAL, which basically fixes the problem
2nd commit changes OPTIONAL to lowercase, eliminating the need of #undef
3rd commit brings most of used enum class to lowercase for consistency.

### CODE REVIEW

**Comment by d-frey** [comment]
Currently the PR seems completely broken, seems like you missed some identifiers. Also, it changes the embedded PEGTL - but the PEGTL should be changed in its own repository first. I'll change the PEGTL shortly, please update your PR afterwards. (Luckily, we are about to update the PEGTL to 3.0.0 anyways so this is a good time to add another breaking change).

**Comment by d-frey** [comment]
I've updated the PEGTL including its documentation and I merged it into taocpp/json. You can now update your patch and once the CI passes, I'll accept the PR. (If updating the PR is too much work just abandon it and create a new one). Thanks.

**Comment by mallexxx** [comment]
Hi, I've updated the commits, so now the tests and gcc builds are passing. Although VS fails to build some tests (same as it did before: 'from_value': no matching overloaded function found and some others)

**Comment by d-frey** [comment]
Please revert the last commit for `from_value` - it's a separate issue and it should not be fixed like this.

**Comment by mallexxx** [comment]
Reverted. Are you planning to fix the MSVS issues or do you have thoughts on how to fix them?

**Comment by ColinH** [comment]
Now that a phase of rapid changes is coming to an end (both regarding features and the C++17 update) our plan is to get VS2017 support back in as soon as possible, and keep things more stable and running on all platforms in the future.

**Comment by ColinH** [comment]
PS: Daniel will fix the other VS issues next week as we are both otherwise occupied this week.

**Pull request merged**
