### PR TITLE
prevent some clang-tidy warnings

### PR DESCRIPTION
**Pull request by ClausKlein**
use cache and clang-tidy while build

 this shows https://github.com/taocpp/json/issues/86

### CODE REVIEW

**Comment by d-frey** [comment]
AFAIK there is a problem with CMake's integration of clang-tidy: It only checks the cpp-files, not the headers. Have you verified that the headers are also checked?

**Comment by ClausKlein** [comment]
> AFAIK there is a problem with CMake's integration of clang-tidy: It only checks the cpp-files, not the headers. Have you verified that the headers are also checked?

Yes, it checks every header, with the same settings as the compiler use.

But normally, I check it after build with `run-clang-tidy` working in `compile-commands.json` generated from cmake.

**Comment by d-frey** [comment]
Looking at the log file: No, it does *not* check every header. It only calls clang-tidy with the .cpp-files. You also output warnings from the headers, but that is *not* the same. The problems are:

* If a header is not included (directly or indirectly) from one of the cpp-files, it won't be checked.
* You will not check if a header is missing an `#include` as thoroughly as you could with checking each header individually with clang-tidy.
* Finally, you blow up the log as each error in a header is reported over and over again - for each cpp file that includes it.

**Comment by ClausKlein** [comment]
> * You will not check if a header is missing an `#include` as thoroughly as you could with checking each header individually with clang-tidy.
> * Finally, you blow up the log as each error in a header is reported over and over again - for each cpp file that includes it.

Yes, that true, but on the other hand, so it use the same compiler options.

If there are #ifdef in header, wich part is checked?
and what about templates, if they are not instantiated?

For the repeated warnings, I use the pip3 builddriver module ...

**Comment by d-frey** [comment]
Using pip3 builddriver: I don't see any of that in the PR. And I don't want to learn yet another tool just to clean up the mess that was unnecessarily created in the first place.

Same compiler options: Which options will make a difference?
Template instantiations: What about it? Show me how it makes a difference in our code.

Seriously, this whole discussion is not going in the right direction. I'm not going to discuss details before we can resolve the main issue: Running clang-tidy on external/*. I stand by my point that this is useless and doesn't help. I presented several arguments, I could add more. If you can not come up with real, specific arguments against this, I will close this PR.

**Comment by ColinH** [comment]
We are responsible for the correctness of all code that we ship as part of our library, and that correctness is ensured by means of unit tests that - implicitly or explicitly - cover the functionality provided by the 3rd-party libraries embedded in our library. We are however not responsible for stylistic choices made by 3rd-party libraries, we are in no position to enforce stylistic choices on 3rd-party libraries, and we have yet to see an argument for any actual benefits of changing embedded 3rd-party code to adhere to our stylistic choices, independent of whether we believe, or not, our choices to be better, or at least better suited to our project.

**Pull request closed without merging**
