### PR TITLE
Add generation of registry file for pkg-config

### PR DESCRIPTION
**Pull request by rherilier**

### CODE REVIEW

**Comment by uilianries** [comment]
@rherilier Thank you for your contribution. Could you please elaborate your need of this PR or point an associated issue? Do you really consume .pc files? What have you doing so far without them?

**Comment by rherilier** [comment]
using pkg-config in Makefile or when communicating a one-line compilation commands for test purpose helps early detection of installed dependency. Using CMake or meson (which can use CMake's registry) for such cases is either irrelevant or not possible.

I admit this MR is not essential for my part.

**Comment by uilianries** [comment]
@rherilier Thank you for your answer. I'll take a look during the weekend to add a new validation using CMake + pkg-config, so we will be good to go.

**Comment by rherilier** [comment]
I simply fixed some typo.

**Comment by rherilier** [comment]
sorry... I did a stupid fix

**Review by uilianries — APPROVED** [review]
LGTM. Tested locally. Thank you for your PR!

```
$ cmake -S . -B build -DCMAKE_INSTALL_PREFIX=/tmp/install -DTAOCPP_JSON_BUILD_TESTS=OFF -DTAOCPP_JSON_BUILD_EXAMPLES=OFF -DTAOCPP_JSON_BUILD_PERFORMANCE=OFF
$ cmake --build build --target install
-- Install configuration: ""
-- Installing: /tmp/install/share/pegtl/cmake/pegtl-config.cmake
-- Installing: /tmp/install/share/pegtl/cmake/pegtl-config-version.cmake
-- Up-to-date: /tmp/install/include
-- Up-to-date: /tmp/install/include/tao
...
 Installing: /tmp/install/share/taocpp-json/cmake/taocpp-json-config.cmake
-- Installing: /tmp/install/share/taocpp-json/cmake/taocpp-json-config-version.cmake
-- Installing: /tmp/install/share/pkgconfig/taocpp-json.pc
-- Installing: /tmp/install/share/taocpp-json/cmake/taocpp-json-targets.cmake
...

$ PKG_CONFIG_PATH=/tmp/install/share/pkgconfig pkg-config taocpp-json --cflags 
-I/tmp/install/include
```

**Comment by rherilier** [comment]
If I read well, the workflows for android run on Ubuntu 22.04 which includes CMake 3.22 and `HOMEPAGE_URL` exists since 3.12...

**Comment by uilianries** [comment]
@rherilier No, it's running 3.10: 

https://github.com/taocpp/json/actions/runs/11018882661/job/30798933170?pr=151#step:4:12

> CMake Error: Could not find cmake module file: /home/developer/build/CMakeFiles/3.10.2/CMakeHOMEPAGE_URLCompiler.cmake

I would ask you reducing your PR to only install the .pc file and its configuration. Nothing more.

The CI looks broken, so I don't want to mix your PR or even block it due that error, so let's be minimal here. Later, I'll revisit to fix the CI and re-introduce that CMake feature. 

Thank you.

**Comment by rherilier** [comment]
@rherilier Thank you for the explanation. 

I'll fix it.

**Comment by uilianries** [comment]
@rherilier Merged. Thank you again!

**Comment by rherilier** [comment]
@uilianries you're welcome ;)

**Pull request merged**
