### PR TITLE
Replaced static with constexpr inline

### PR DESCRIPTION
**Pull request by matbech**
Removed static as it duplicates the data in every translation unit.

### CODE REVIEW

**Comment by ColinH** [comment]
@d-frey Any reason not to merge this?

**Comment by d-frey** [comment]
I'm a little bit conflicted about this. The PR itself is, of course, OK.

But it affects 3rd-party-code, hence it should go into RYU - unless we have modified the code anyways. I would rather prefer to have it fixed upstream and then update our copy. Or replace it by `<charconv>`. Damn, this is all a big mess. 😞

Anyways, I'll leave it to you @ColinH to decide, I'm too busy with taoPQ right now to tackle a cleanup of the whole conversion stuff in taoJSON 😊

**Comment by ColinH** [comment]
Upstream is C, not C++, so we can merge this ... and of course revisit charconv later and see how far the implementations have come.

**Comment by ColinH** [comment]
@matbech Thank you!

**Pull request merged**
